tasks:
  - init: |
      echo 'Installing dependencies.'
      cd catch-of-the-day
      npm install
      npx -y install-peerdeps --dev eslint-config-wesbos
    command: |
      echo 'Running the dev app'
      cd catch-of-the-day
      npm run dev
ports:
  - port: 3000
    onOpen: open-preview
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
