tasks:
  - init: |
      echo 'Installing dependencies.'
      npm install
    command: |
      echo 'Running the dev app'
      npm run dev
ports:
  - port: 3000
    onOpen: open-preview
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
